# declare and configure kinematic solver

arm:
  kinematic_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.05
  kinematics_solver_timeout: 0.005
  position_only_ik: True